### ISSUE TITLE
resizing moves pieces incorrectly in some cases

### ISSUE THREAD

**Issue by csells** [justinmc/flutter-go#1]
the attached animated gif tells the tale

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2568253/88752519-fe096f80-d10e-11ea-9bcf-95b484281a4a.gif)

**Comment by justinmc** [comment]
Fixed in https://github.com/justinmc/flutter-go/commit/24452241b52c15c29069513dccb8fd5aa0289620!
