### ISSUE TITLE
resizing issue with pieces on the new board

### ISSUE THREAD

**Issue by csells** [justinmc/flutter-go#2]
see attached

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2568253/88859778-4f693b80-d1af-11ea-931a-9083356fa03f.gif)

**Comment by justinmc** [comment]
Fixed with https://github.com/justinmc/flutter-go/commit/8f8fce67b9d9cc74b91008fc25efc1b4e1552871

I hard coded the aspect ratio of the board.  I could do it dynamically if you think it's worth it.

**Comment by csells** [comment]
Is there any downside to calculating it dynamically? That seems like the more robust way to solve the problem. What if I didn't use an image but instead drew the board? What if the image was dynamic?

**Comment by justinmc** [comment]
It should definitely be dynamic, the hardcoding was a hack.  I'll reopen this to track it.

**Comment by justinmc** [comment]
Alright I made it dynamic in https://github.com/justinmc/flutter-go/commit/75fce4ab7285bb22bbd123971c2bb74eeeb5b352.
