### ISSUE TITLE
Add a web demo

### ISSUE THREAD

**Issue by tusharsadhwani** [justinmc/flutter-go#4]
If the app compiles for web with no issues, a web demo on github pages would be pretty neat

here's the simple plug-n-play github action i made for it: [Source](https://github.com/tusharsadhwani/mines/blob/master/.github/workflows/flutter.yml)

PS. adding the deployment key required for the action can be referred from [this guide](https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b)

**Comment by justinmc** [comment]
Sorry I missed this issue for so long, this is a great idea.  I usually try to manually set up a github pages demo for projects like this, but I wasn't even aware of Github's ability to automatically deploy that.  I followed your instructions and it seems to work great.  Thanks again for this. https://justinmc.github.io/flutter-go/
